name: Fetch latest versions from Live2D

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
          
      - name: Setup OSSUTIL environment
        uses: yizhoumo/setup-ossutil@v1.0.2
        with:
          endpoint: ${{ secrets.OSS_ENDPOINT }}
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      
      - name: Generate links and versions
        run: |
          cd crawler
          node app.js
          
      - name: If there is a new version, update the file
        run: |
          cd crawler
          chmod +x update.sh
          ./update.sh
